import { useEffect, useState } from "react";

const rows = [
  ["R-0247", "ROUND_COMPLETE", "8", "Mira", "325", "J-1005"],
  ["R-0246", "REFUNDED", "4", "—", "0", "J-1004"],
  ["R-0245", "ROUND_COMPLETE", "10", "Jordan", "-250", "J-1003"]
];
const ledger = [
  ["J-1005", "ROUND_SETTLEMENT", "USER_LOCKED → USER_AVAILABLE", "+325", "R-0247"],
  ["J-1004", "BET_LOCK", "USER_AVAILABLE → USER_LOCKED", "250", "R-0247"],
  ["J-1003", "MISSION_REWARD", "DEMO_GRANTS → USER_AVAILABLE", "+120", "M-DAILY"]
];

export default function App() {
  const [page, setPage] = useState("Dashboard");
  const [notice, setNotice] = useState("");
  const [apiStatus, setApiStatus] = useState<"loading" | "connected" | "fallback">("loading");
  const [liveRounds, setLiveRounds] = useState(0);
  const [liveAudit, setLiveAudit] = useState(0);
  const adminToken = import.meta.env.VITE_ADMIN_DEMO_TOKEN ?? (import.meta.env.DEV ? "admin-demo-only" : "");
  const apiUrl = (import.meta.env.VITE_API_URL ?? "http://localhost:8787").replace(/\/$/, "");
  useEffect(() => { const apiUrl = import.meta.env.VITE_API_URL ?? "http://localhost:8787"; const headers = adminToken ? { "x-demo-admin-token": adminToken } : undefined; void Promise.all(["rounds", "audit-logs"].map((resource) => fetch(`${apiUrl}/api/admin/${resource}`, headers ? { headers } : undefined).then((response) => response.ok ? response.json() as Promise<unknown[]> : Promise.reject(new Error("admin api unavailable"))))).then(([rounds, audit]) => { setLiveRounds(rounds.length); setLiveAudit(audit.length); setApiStatus("connected"); }).catch(() => setApiStatus("fallback")); }, []);
  const action = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };
  return <div className="admin-shell"><aside><div className="admin-brand"><span>P12</span><div><b>PROJECT 12</b><small>Operations Console</small></div></div><div className="admin-mode">PRODUCTION CONTROL · LOCKED · {apiStatus === "connected" ? "API LIVE" : "SERVICE UNAVAILABLE"}</div><nav>{["Dashboard", "Verification", "Rounds", "Jobs", "Rules", "Users", "Devices", "Ledger", "Campaigns", "Announcements", "Disputes", "Audit logs", "Settings"].map(item => <button key={item} className={page === item ? "active" : ""} onClick={() => setPage(item)}>{item}<span>›</span></button>)}</nav><div className="admin-user"><span className="admin-avatar">SA</span><div><b>Safety Admin</b><small>SUPER_ADMIN · read/write</small></div></div></aside><main><header><div><span className="kicker">OPERATIONS / {page.toUpperCase()}</span><h1>{page}</h1></div><button className="outline-button" onClick={() => action("Payment controls are unavailable until the production service is configured")}>Payment controls locked</button></header>{page === "Dashboard" && <AdminOverview apiUrl={apiUrl} adminToken={adminToken} action={action} />}{page === "Verification" && <Verifications apiUrl={apiUrl} adminToken={adminToken} action={action} />}{page === "Rounds" && <AdminLiveRoom apiUrl={apiUrl} adminToken={adminToken} action={action} />}{page === "Jobs" && <AdminJobs apiUrl={apiUrl} adminToken={adminToken} />}{page === "Rules" && <AdminRules apiUrl={apiUrl} adminToken={adminToken} />}{page === "Ledger" && <AdminLedger apiUrl={apiUrl} adminToken={adminToken} />}{page === "Users" && <Users />}{page === "Devices" && <Devices />}{page === "Campaigns" && <Campaigns action={action} />}{page === "Announcements" && <Announcements action={action} />}{page === "Disputes" && <Disputes action={action} />}{page === "Audit logs" && <AdminAudit apiUrl={apiUrl} adminToken={adminToken} />}{page === "Settings" && <Settings action={action} />}{notice && <div className="notice">{notice}</div>}</main></div>;
}

type VerificationCase = { telegramUserId: string; legalName?: string; tngAccountMasked?: string; status: string; submittedAt?: string; rejectionReason?: string };

function Verifications({ apiUrl, adminToken, action }: { apiUrl: string; adminToken: string; action: (message: string) => void }) {
  const [cases, setCases] = useState<VerificationCase[]>([]);
  const [loading, setLoading] = useState(true);
  const headers = { "x-demo-admin-token": adminToken };
  const refresh = () => { setLoading(true); void fetch(`${apiUrl}/api/admin/verifications?status=PENDING`, { headers }).then((response) => response.ok ? response.json() as Promise<VerificationCase[]> : Promise.reject(new Error("verification api unavailable"))).then(setCases).catch(() => setCases([])).finally(() => setLoading(false)); };
  useEffect(refresh, [apiUrl, adminToken]);
  const review = (item: VerificationCase, status: "APPROVED" | "REJECTED" | "NEEDS_MORE_INFO") => { const key = `admin-verification-${item.telegramUserId}-${status}-${Date.now()}`; void fetch(`${apiUrl}/api/admin/verification/${encodeURIComponent(item.telegramUserId)}/review`, { method: "POST", headers: { ...headers, "content-type": "application/json", "idempotency-key": key }, body: JSON.stringify({ status }) }).then((response) => response.ok ? undefined : Promise.reject(new Error("review failed"))).then(() => { action(`${item.telegramUserId} · ${status}`); refresh(); }).catch(() => action("审核请求失败，请检查 Admin API")); };
  return <section className="panel"><div className="panel-head"><div><span className="kicker">KYC / PRIVATE DATA</span><h2>Pending verification</h2></div><span className="state settled">{loading ? "LOADING" : `${cases.length} PENDING`}</span></div>{!loading && cases.length === 0 && <p>No pending verification cases. Production Admin data is never replaced by sample rows.</p>}<div className="verification-admin-list">{cases.map((item) => <article className="verification-admin-row" key={item.telegramUserId}><div><b>{item.legalName ?? "Name available to reviewer"}</b><small>Telegram {item.telegramUserId} · {item.tngAccountMasked ?? "••••"}</small><small>{item.submittedAt ? new Date(item.submittedAt).toLocaleString() : "—"}</small></div><div className="verification-admin-actions"><button className="outline-button" onClick={() => review(item, "NEEDS_MORE_INFO")}>More info</button><button className="outline-button" onClick={() => review(item, "REJECTED")}>Reject</button><button className="primary-admin" onClick={() => review(item, "APPROVED")}>Approve</button></div></article>)}</div></section>;
}

type AdminProps = { apiUrl: string; adminToken: string };
type OverviewPayload = { room: { id: string; name: string; state: string; roundId: string; banker: string; players: number; bankPool: number; endsAt?: string }; counts: { messages: number; roundEvents: number; pendingOutbox: number; riskFlags: number; bettors: number }; database: string; databaseConfigured: boolean; worker: { status: string; workerId?: string; heartbeatAt?: string; mode?: string }; invariants: { ledgerBalanced: boolean; internalPacketOnly: boolean; productionWritesDisabled: boolean } };
function useAdminFetch<T>(url: string, token: string) {
  const [data, setData] = useState<T | undefined>();
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; setLoading(true); void fetch(url, { headers: token ? { "x-demo-admin-token": token } : undefined, cache: "no-store" }).then((response) => response.ok ? response.json() as Promise<T> : Promise.reject(new Error("admin api unavailable"))).then((value) => { if (active) setData(value); }).catch(() => { if (active) setData(undefined); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [url, token]);
  return { data, loading };
}
function AdminOverview({ apiUrl, adminToken, action }: AdminProps & { action: (message: string) => void }) {
  const { data, loading } = useAdminFetch<OverviewPayload>(`${apiUrl}/api/admin/overview`, adminToken);
  const counts = data?.counts;
  const health = data ? [["API", "Healthy", data.database], ["Worker", data.worker.status, data.worker.mode ?? "runtime"], ["Packet", data.invariants.internalPacketOnly ? "Internal only" : "Review", "no cash"], ["Ledger", data.invariants.ledgerBalanced ? "Balanced" : "Drift", "invariant"]] : [];
  return <><section className="metric-grid">{[["Live room", data?.room.state ?? "—", data?.room.roundId ?? "loading"], ["Players", String(data?.room.players ?? "—"), "current room"], ["Messages", String(counts?.messages ?? "—"), "monotonic seq"], ["Outbox", String(counts?.pendingOutbox ?? "—"), "pending"]].map(([label, value, change]) => <div className="metric" key={label}><span>{label}</span><strong>{loading ? "…" : value}</strong><small>{change}</small></div>)}</section><section className="split-grid"><div className="panel"><div className="panel-head"><div><span className="kicker">LIVE CONTROL ROOM</span><h2>{data?.room.name ?? "Room overview"}</h2></div><button className="link-button" onClick={() => action("Live room inspector opened")}>Open inspector →</button></div><div className="health-grid">{[["State", data?.room.state ?? "—", data?.room.endsAt ?? "—"], ["Banker", data?.room.banker ?? "—", "authoritative"], ["Bettors", String(counts?.bettors ?? "—"), "current round"], ["Risk queue", String(counts?.riskFlags ?? "—"), "requires review"]].map((item) => <div key={item[0]}><span className="health-icon">{item[0] === "Risk queue" && Number(item[1]) > 0 ? "!" : "✓"}</span><div><b>{item[0]}</b><small>{item[1]} · {item[2]}</small></div></div>)}</div></div><div className="panel"><div className="panel-head"><div><span className="kicker">RUNTIME INVARIANTS</span><h2>Safety gates</h2></div><span className="state settled">{data?.invariants.productionWritesDisabled ? "STAGING" : "REVIEW"}</span></div>{health.map((item) => <div className="setting-row" key={item[0]}><span>{item[0]}</span><b>{item[1]} · {item[2]}</b></div>)}</div></section></>;
}
type LivePayload = { room: OverviewPayload["room"]; worker: OverviewPayload["worker"]; messages: Array<{ id: string; messageSeq?: number; type: string; body: string; createdAt: string }>; events: Array<{ id: string; from?: string; to: string; createdAt: string }> };
function AdminLiveRoom({ apiUrl, adminToken, action }: AdminProps & { action: (message: string) => void }) {
  const { data, loading } = useAdminFetch<LivePayload>(`${apiUrl}/api/admin/rooms/room-12/live`, adminToken);
  return <section className="panel detail-panel"><div className="panel-head"><div><span className="kicker">LIVE INSPECTOR / ROOM-12</span><h2>{data?.room.roundId ?? "Loading room"}</h2></div><button className="outline-button" onClick={() => action("Admin transitions require a reviewed ticket")}>Controlled transition</button></div><p>{data?.room.state ?? "Loading"} · banker {data?.room.banker ?? "—"} · {data?.room.players ?? 0} players · worker {data?.worker.status ?? "—"}</p>{loading && <p>Loading authoritative room data…</p>}<div className="timeline">{(data?.events ?? []).slice(0, 12).map((item) => <div className="timeline-item" key={item.id}><span className="timeline-dot"/><div><small>{new Date(item.createdAt).toLocaleTimeString()} · {item.from ?? "—"} → {item.to}</small><b>Round state transition recorded</b></div></div>)}</div><div className="audit-list">{(data?.messages ?? []).slice(-12).map((message) => <div key={message.id}><b>#{message.messageSeq ?? "—"}</b><span>{message.type}</span><small>{message.body}</small></div>)}</div></section>;
}
function AdminLedger({ apiUrl, adminToken }: AdminProps) { const { data, loading } = useAdminFetch<Array<{ id: string; reason: string; change: number; balanceAfter: number; createdAt: string }>>(`${apiUrl}/api/admin/ledger`, adminToken); return <section className="panel"><div className="panel-head"><div><span className="kicker">APPEND-ONLY DOUBLE ENTRY</span><h2>Ledger journals</h2></div><span className="state settled">{loading ? "LOADING" : "BALANCED · INTERNAL"}</span></div>{!loading && !data?.length && <p>No ledger journals are available.</p>}<div className="audit-list">{(data ?? []).map((entry) => <div key={entry.id}><b>{entry.id}</b><span>{entry.change >= 0 ? "+" : ""}{entry.change} PT</span><small>{entry.reason} · balance {entry.balanceAfter}</small></div>)}</div></section>; }
function AdminAudit({ apiUrl, adminToken }: AdminProps) { const { data, loading } = useAdminFetch<Array<{ id: string; action: string; actor: string; referenceId: string; createdAt: string }>>(`${apiUrl}/api/admin/audit-logs`, adminToken); return <section className="panel"><div className="panel-head"><div><span className="kicker">IMMUTABLE HISTORY</span><h2>Audit logs</h2></div><span className="state settled">{loading ? "LOADING" : `${data?.length ?? 0} EVENTS`}</span></div>{!loading && !data?.length && <p>No audit events recorded yet.</p>}<div className="audit-list">{(data ?? []).map((entry) => <div key={entry.id}><b>{entry.id}</b><span>{entry.action}</span><small>{entry.actor} · {entry.referenceId} · {new Date(entry.createdAt).toLocaleString()}</small></div>)}</div></section>; }
type JobsPayload = { worker: { status: string; workerId?: string; heartbeatAt?: string; mode?: string }; pendingOutbox: Array<{ id: string; type: string; createdAt: string }>; currentRound?: { id: string; state: string; stateEndsAt?: string }; lastRoundEvents: Array<{ id: string; to: string; createdAt: string }> };
function AdminJobs({ apiUrl, adminToken }: AdminProps) { const { data, loading } = useAdminFetch<JobsPayload>(`${apiUrl}/api/admin/jobs`, adminToken); return <section className="panel detail-panel"><div className="panel-head"><div><span className="kicker">DURABLE EXECUTION / OUTBOX</span><h2>Worker jobs</h2></div><span className={`state ${data?.worker.status === "healthy" ? "settled" : "held"}`}>{loading ? "LOADING" : data?.worker.status?.toUpperCase() ?? "UNKNOWN"}</span></div><div className="setting-row"><span>Worker</span><b>{data?.worker.workerId ?? "—"} · {data?.worker.mode ?? "—"}</b></div><div className="setting-row"><span>Heartbeat</span><b>{data?.worker.heartbeatAt ? new Date(data.worker.heartbeatAt).toLocaleString() : "—"}</b></div><div className="setting-row"><span>Current round</span><b>{data?.currentRound?.id ?? "—"} · {data?.currentRound?.state ?? "—"}</b></div><h3>Pending outbox</h3>{!loading && !data?.pendingOutbox.length && <p>Outbox is empty. No unpublished side effects are waiting.</p>}<div className="audit-list">{(data?.pendingOutbox ?? []).map((entry) => <div key={entry.id}><b>{entry.id}</b><span>{entry.type}</span><small>{new Date(entry.createdAt).toLocaleString()}</small></div>)}</div></section>; }
function AdminRules({ apiUrl, adminToken }: AdminProps) { const { data, loading } = useAdminFetch<Array<{ id: string; version: string; status: string; immutable: boolean; demoOnly: boolean; rules: Record<string, unknown> }>>(`${apiUrl}/api/admin/rules`, adminToken); return <section className="panel detail-panel"><div className="panel-head"><div><span className="kicker">IMMUTABLE RULE VERSION</span><h2>Game rules</h2></div><span className="state settled">{loading ? "LOADING" : data?.[0]?.status ?? "—"}</span></div>{(data ?? []).map((entry) => <div key={entry.id}><div className="setting-row"><span>Version</span><b>{entry.version} · {entry.immutable ? "immutable" : "editable"}</b></div><div className="setting-row"><span>Mode</span><b>{entry.demoOnly ? "Internal points only" : "Production"}</b></div><pre>{JSON.stringify(entry.rules, null, 2)}</pre></div>)}</section>; }

function Dashboard({ action, liveRounds, liveAudit }: { action: (message: string) => void; liveRounds: number; liveAudit: number }) { return <><section className="metric-grid">{[["Active users", "128", "+12%"], ["Live rounds", String(liveRounds || 4), liveRounds ? "API" : "fallback"], ["Internal turnover", "48,250", "points"], ["Audit events", String(liveAudit || 3), liveAudit ? "API" : "fallback"]].map(([label, value, change]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{change}</small></div>)}</section><section className="split-grid"><div className="panel"><div className="panel-head"><div><span className="kicker">LIVE CONTROL ROOM</span><h2>Current rounds</h2></div><button className="link-button" onClick={() => action("Round timeline opened")}>View timeline →</button></div><table><thead><tr><th>Round</th><th>State</th><th>Players</th><th>Banker</th><th>Audit</th></tr></thead><tbody>{rows.map(row => <tr key={row[0]}><td><b>{row[0]}</b></td><td><span className={`state ${row[1].toLowerCase()}`}>{row[1]}</span></td><td>{row[2]}</td><td>{row[3]}</td><td><button className="row-link" onClick={() => action(`Opened ${row[5]}`)}>{row[5]} ↗</button></td></tr>)}</tbody></table></div><div className="panel risk-panel"><div className="panel-head"><div><span className="kicker">RISK QUEUE</span><h2>Needs review</h2></div><span className="count">3</span></div>{[["RF-019", "Repeated referral pairing", "REVIEW"], ["RF-018", "Fast round completion", "HELD"], ["RF-017", "Shared browser signal", "REVIEW"]].map(item => <button className="risk-row" key={item[0]} onClick={() => action(`${item[0]} opened`)}><span className="risk-dot"/><div><b>{item[0]}</b><small>{item[1]}</small></div><span className="risk-tag">{item[2]}</span></button>)}</div></section><section className="panel"><div className="panel-head"><div><span className="kicker">HEALTH</span><h2>Service guardrails</h2></div><span className="state settled">ALL SAFE</span></div><div className="health-grid">{[["API", "Healthy", "99.98%"], ["Worker", "Healthy", "1 active"], ["Bot", "Not configured", "server required"], ["Ledger", "Balanced", "0 drift"]].map(item => <div key={item[0]}><span className="health-icon">✓</span><div><b>{item[0]}</b><small>{item[1]} · {item[2]}</small></div></div>)}</div></section></>; }

function Rounds({ action }: { action: (message: string) => void }) { return <section className="panel detail-panel"><div className="panel-head"><div><span className="kicker">ROUND AUDIT</span><h2>R-0247 · state timeline</h2></div><button className="outline-button" onClick={() => action("Round marked for review")}>Open dispute</button></div><div className="timeline">{[["14:31:02", "BETTING", "8 players joined; bets locked server-side"], ["14:31:30", "PACKET_SENT", "Provider packet created and seed hash published"], ["14:32:00", "CLAIMING", "Claim window opened"], ["14:32:15", "EVALUATING", "Claims ordered by claimed_at"], ["14:32:45", "SETTLING", "Ledger journal J-1005 created"], ["14:32:46", "ROUND_COMPLETE", "Audit log written; result published"]].map(item => <div className="timeline-item" key={item[0]}><span className="timeline-dot"/><div><small>{item[0]} · {item[1]}</small><b>{item[2]}</b></div></div>)}</div></section>; }
function Ledger() { return <section className="panel"><div className="panel-head"><div><span className="kicker">APPEND-ONLY DOUBLE ENTRY</span><h2>Ledger journals</h2></div><span className="state settled">BALANCED</span></div><table><thead><tr><th>Journal</th><th>Reference</th><th>Accounts</th><th>Amount</th><th>Round</th></tr></thead><tbody>{ledger.map(row => <tr key={row[0]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td className="amount">{row[3]}</td><td>{row[4]}</td></tr>)}</tbody></table></section>; }
function Users() { return <section className="panel"><div className="panel-head"><div><span className="kicker">IDENTITY & RISK</span><h2>Users</h2></div><span className="state settled">NO CASH VALUE</span></div><table><thead><tr><th>User</th><th>Telegram identity</th><th>Available</th><th>Locked</th><th>Risk</th></tr></thead><tbody>{[["Alex Tan", "player-01", "12,500", "250", "CLEAR"], ["Mira", "banker-01", "24,800", "4,800", "CLEAR"], ["Jordan", "player-02", "3,200", "0", "REVIEW"]].map(row => <tr key={row[1]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><span className={`risk-tag ${row[4].toLowerCase()}`}>{row[4]}</span></td></tr>)}</tbody></table></section>; }
function Devices() { return <section className="panel"><div className="panel-head"><div><span className="kicker">DEVICE TRUST</span><h2>Bound devices</h2></div><span className="state settled">1 ACTIVE</span></div><table><thead><tr><th>User</th><th>Device</th><th>Platform</th><th>Last seen</th><th>Recovery</th></tr></thead><tbody>{[["Alex Tan", "device_8fa2…", "Telegram iOS", "2 min ago", "—"], ["Jordan", "device_31bb…", "Telegram Android", "18 min ago", "OPEN"]].map(row => <tr key={row[1]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><span className={`risk-tag ${row[4] === "—" ? "clear" : "review"}`}>{row[4]}</span></td></tr>)}</tbody></table><p>一账号一主要设备。换绑只能通过受控 recovery 流程，并写入审计日志。</p></section>; }
function Campaigns({ action }: { action: (message: string) => void }) { return <section className="panel campaign-panel"><div className="panel-head"><div><span className="kicker">VERSIONED REWARDS</span><h2>Campaigns</h2></div><button className="primary-admin" onClick={() => action("Draft campaign created")}>Create draft</button></div>{[["Daily banker count", "v2 · active", "1,240 / 2,000"], ["Special hand collection", "v1 · active", "68 / 100"], ["Referral qualification", "v3 · paused", "24 / 50"]].map(row => <div className="campaign-row" key={row[0]}><div><b>{row[0]}</b><small>{row[1]}</small></div><span>{row[2]}</span><button className="row-link" onClick={() => action(`${row[0]} opened`)}>Manage →</button></div>)}</section>; }
function Announcements({ action }: { action: (message: string) => void }) { return <section className="panel campaign-panel"><div className="panel-head"><div><span className="kicker">CONTENT CONTROL</span><h2>Announcements</h2></div><button className="primary-admin" onClick={() => action("Announcement draft created")}>Create draft</button></div>{[["Round centre is live", "PUBLISHED", "Today · 09:00"], ["Scheduled maintenance", "DRAFT", "Tomorrow · 02:00"], ["Internal points notice", "PUBLISHED", "Aug 18 · 15:30"]].map(row => <div className="campaign-row" key={row[0]}><div><b>{row[0]}</b><small>{row[2]}</small></div><span className={`state ${row[1].toLowerCase()}`}>{row[1]}</span><button className="row-link" onClick={() => action(`${row[0]} opened`)}>Manage →</button></div>)}</section>; }
function Disputes({ action }: { action: (message: string) => void }) { return <section className="panel"><div className="panel-head"><div><span className="kicker">CONTROLLED EXCEPTIONS</span><h2>Disputes</h2></div></div><div className="dispute-card"><span className="risk-tag held">OPEN</span><h3>DS-004 · delayed settlement</h3><p>Player reports a missing settlement. No loss is assumed before the ledger is confirmed.</p><div><button className="outline-button" onClick={() => action("Dispute moved to review")}>Review</button><button className="primary-admin" onClick={() => action("Refund workflow prepared")}>Prepare refund</button></div></div></section>; }
function Audit({ action }: { action: (message: string) => void }) { return <section className="panel"><div className="panel-head"><div><span className="kicker">IMMUTABLE HISTORY</span><h2>Audit logs</h2></div><button className="outline-button" onClick={() => action("Export requires a reviewed admin action")}>Export unavailable</button></div><div className="audit-list">{[["AL-9921", "ROUND_SETTLED", "Safety Admin", "R-0247"], ["AL-9920", "CLAIM_WINDOW_OPENED", "Worker", "R-0247"], ["AL-9919", "RISK_FLAG_CREATED", "Risk Reviewer", "RF-019"]].map(row => <div key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><small>{row[2]} · {row[3]}</small></div>)}</div></section>; }
function Settings({ action }: { action: (message: string) => void }) { return <section className="panel settings-admin"><div className="panel-head"><div><span className="kicker">GUARDRAILS</span><h2>System configuration</h2></div><span className="state settled">SAFE DEFAULTS</span></div>{[["Real-money operations", "Disabled"], ["TNG integration", "Disabled"], ["Packet provider", "InternalPacketProvider"], ["Telegram auth", "Signed initData required"]].map(row => <div className="setting-row" key={row[0]}><span>{row[0]}</span><b>{row[1]}</b></div>)}<button className="outline-button" onClick={() => action("Configuration changes require a reviewed admin action")}>Request reviewed change</button></section>; }
