import { useState } from "react";

const rows = [
  ["R-0247", "SETTLED", "8", "Mira", "325", "J-1005"],
  ["R-0246", "REFUNDED", "4", "—", "0", "J-1004"],
  ["R-0245", "SETTLED", "10", "Jordan", "-250", "J-1003"]
];
const ledger = [
  ["J-1005", "ROUND_SETTLEMENT", "USER_LOCKED → USER_AVAILABLE", "+325", "R-0247"],
  ["J-1004", "BET_LOCK", "USER_AVAILABLE → USER_LOCKED", "250", "R-0247"],
  ["J-1003", "MISSION_REWARD", "DEMO_GRANTS → USER_AVAILABLE", "+120", "M-DAILY"]
];

export default function App() {
  const [page, setPage] = useState("Dashboard");
  const [notice, setNotice] = useState("");
  const action = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };
  return <div className="admin-shell"><aside><div className="admin-brand"><span>P12</span><div><b>PROJECT 12</b><small>Operations Console</small></div></div><div className="admin-mode">DEMO MODE · LOCKED</div><nav>{["Dashboard", "Rounds", "Users", "Devices", "Ledger", "Campaigns", "Announcements", "Disputes", "Audit logs", "Settings"].map(item => <button key={item} className={page === item ? "active" : ""} onClick={() => setPage(item)}>{item}<span>›</span></button>)}</nav><div className="admin-user"><span className="admin-avatar">SA</span><div><b>Safety Admin</b><small>SUPER_ADMIN · read/write</small></div></div></aside><main><header><div><span className="kicker">OPERATIONS / {page.toUpperCase()}</span><h1>{page}</h1></div><button className="outline-button" onClick={() => action("No payment action is available in demo mode")}>Payment controls locked</button></header>{page === "Dashboard" && <Dashboard action={action} />}{page === "Rounds" && <Rounds action={action} />}{page === "Ledger" && <Ledger />}{page === "Users" && <Users />}{page === "Devices" && <Devices />}{page === "Campaigns" && <Campaigns action={action} />}{page === "Announcements" && <Announcements action={action} />}{page === "Disputes" && <Disputes action={action} />}{page === "Audit logs" && <Audit action={action} />}{page === "Settings" && <Settings action={action} />}{notice && <div className="notice">{notice}</div>}</main></div>;
}

function Dashboard({ action }: { action: (message: string) => void }) { return <><section className="metric-grid">{[["Active users", "128", "+12%"], ["Live rounds", "4", "stable"], ["Demo turnover", "48,250", "points"], ["Open risk alerts", "3", "review"]].map(([label, value, change]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{change}</small></div>)}</section><section className="split-grid"><div className="panel"><div className="panel-head"><div><span className="kicker">LIVE CONTROL ROOM</span><h2>Current rounds</h2></div><button className="link-button" onClick={() => action("Round timeline opened")}>View timeline →</button></div><table><thead><tr><th>Round</th><th>State</th><th>Players</th><th>Banker</th><th>Audit</th></tr></thead><tbody>{rows.map(row => <tr key={row[0]}><td><b>{row[0]}</b></td><td><span className={`state ${row[1].toLowerCase()}`}>{row[1]}</span></td><td>{row[2]}</td><td>{row[3]}</td><td><button className="row-link" onClick={() => action(`Opened ${row[5]}`)}>{row[5]} ↗</button></td></tr>)}</tbody></table></div><div className="panel risk-panel"><div className="panel-head"><div><span className="kicker">RISK QUEUE</span><h2>Needs review</h2></div><span className="count">3</span></div>{[["RF-019", "Repeated referral pairing", "REVIEW"], ["RF-018", "Fast round completion", "HELD"], ["RF-017", "Shared browser signal", "REVIEW"]].map(item => <button className="risk-row" key={item[0]} onClick={() => action(`${item[0]} opened`)}><span className="risk-dot"/><div><b>{item[0]}</b><small>{item[1]}</small></div><span className="risk-tag">{item[2]}</span></button>)}</div></section><section className="panel"><div className="panel-head"><div><span className="kicker">HEALTH</span><h2>Service guardrails</h2></div><span className="state settled">ALL SAFE</span></div><div className="health-grid">{[["API", "Healthy", "99.98%"], ["Worker", "Healthy", "1 active"], ["Bot", "Mock only", "token absent"], ["Ledger", "Balanced", "0 drift"]].map(item => <div key={item[0]}><span className="health-icon">✓</span><div><b>{item[0]}</b><small>{item[1]} · {item[2]}</small></div></div>)}</div></section></>; }

function Rounds({ action }: { action: (message: string) => void }) { return <section className="panel detail-panel"><div className="panel-head"><div><span className="kicker">ROUND AUDIT</span><h2>R-0247 · state timeline</h2></div><button className="outline-button" onClick={() => action("Round marked for review")}>Open dispute</button></div><div className="timeline">{[["14:31:02", "BETTING", "8 players joined; bets locked server-side"], ["14:31:30", "DEMO_PACKET_READY", "Seed hash published to clients"], ["14:32:00", "CLAIMING", "Claim window opened"], ["14:32:45", "SETTLING", "Ledger journal J-1005 created"], ["14:32:46", "SETTLED", "Audit log written; result published"]].map(item => <div className="timeline-item" key={item[0]}><span className="timeline-dot"/><div><small>{item[0]} · {item[1]}</small><b>{item[2]}</b></div></div>)}</div></section>; }
function Ledger() { return <section className="panel"><div className="panel-head"><div><span className="kicker">APPEND-ONLY DOUBLE ENTRY</span><h2>Ledger journals</h2></div><span className="state settled">BALANCED</span></div><table><thead><tr><th>Journal</th><th>Reference</th><th>Accounts</th><th>Amount</th><th>Round</th></tr></thead><tbody>{ledger.map(row => <tr key={row[0]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td className="amount">{row[3]}</td><td>{row[4]}</td></tr>)}</tbody></table></section>; }
function Users() { return <section className="panel"><div className="panel-head"><div><span className="kicker">IDENTITY & RISK</span><h2>Demo users</h2></div><span className="state settled">NO CASH VALUE</span></div><table><thead><tr><th>User</th><th>Telegram identity</th><th>Available</th><th>Locked</th><th>Risk</th></tr></thead><tbody>{[["Alex Tan", "demo-player-01", "12,500", "250", "CLEAR"], ["Mira", "demo-banker-01", "24,800", "4,800", "CLEAR"], ["Jordan", "demo-player-02", "3,200", "0", "REVIEW"]].map(row => <tr key={row[1]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><span className={`risk-tag ${row[4].toLowerCase()}`}>{row[4]}</span></td></tr>)}</tbody></table></section>; }
function Devices() { return <section className="panel"><div className="panel-head"><div><span className="kicker">DEVICE TRUST</span><h2>Bound devices</h2></div><span className="state settled">1 ACTIVE</span></div><table><thead><tr><th>User</th><th>Device</th><th>Platform</th><th>Last seen</th><th>Recovery</th></tr></thead><tbody>{[["Alex Tan", "device_8fa2…", "Telegram iOS", "2 min ago", "—"], ["Jordan", "device_31bb…", "Telegram Android", "18 min ago", "OPEN"]].map(row => <tr key={row[1]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><span className={`risk-tag ${row[4] === "—" ? "clear" : "review"}`}>{row[4]}</span></td></tr>)}</tbody></table><p>一账号一主要设备。换绑只能通过受控 recovery 流程，并写入审计日志。</p></section>; }
function Campaigns({ action }: { action: (message: string) => void }) { return <section className="panel campaign-panel"><div className="panel-head"><div><span className="kicker">VERSIONED REWARDS</span><h2>Campaigns</h2></div><button className="primary-admin" onClick={() => action("Draft campaign created")}>Create draft</button></div>{[["Daily banker count", "v2 · active", "1,240 / 2,000"], ["Special hand collection", "v1 · active", "68 / 100"], ["Referral qualification", "v3 · paused", "24 / 50"]].map(row => <div className="campaign-row" key={row[0]}><div><b>{row[0]}</b><small>{row[1]}</small></div><span>{row[2]}</span><button className="row-link" onClick={() => action(`${row[0]} opened`)}>Manage →</button></div>)}</section>; }
function Announcements({ action }: { action: (message: string) => void }) { return <section className="panel campaign-panel"><div className="panel-head"><div><span className="kicker">CONTENT CONTROL</span><h2>Announcements</h2></div><button className="primary-admin" onClick={() => action("Announcement draft created")}>Create draft</button></div>{[["Round centre is live", "PUBLISHED", "Today · 09:00"], ["Scheduled maintenance", "DRAFT", "Tomorrow · 02:00"], ["Demo safety notice", "PUBLISHED", "Aug 18 · 15:30"]].map(row => <div className="campaign-row" key={row[0]}><div><b>{row[0]}</b><small>{row[2]}</small></div><span className={`state ${row[1].toLowerCase()}`}>{row[1]}</span><button className="row-link" onClick={() => action(`${row[0]} opened`)}>Manage →</button></div>)}</section>; }
function Disputes({ action }: { action: (message: string) => void }) { return <section className="panel"><div className="panel-head"><div><span className="kicker">CONTROLLED EXCEPTIONS</span><h2>Disputes</h2></div></div><div className="dispute-card"><span className="risk-tag held">OPEN</span><h3>DS-004 · delayed settlement</h3><p>Player reports a missing settlement. No loss is assumed before the ledger is confirmed.</p><div><button className="outline-button" onClick={() => action("Dispute moved to review")}>Review</button><button className="primary-admin" onClick={() => action("Refund workflow prepared")}>Prepare refund</button></div></div></section>; }
function Audit({ action }: { action: (message: string) => void }) { return <section className="panel"><div className="panel-head"><div><span className="kicker">IMMUTABLE HISTORY</span><h2>Audit logs</h2></div><button className="outline-button" onClick={() => action("Export is disabled in demo mode")}>Export disabled</button></div><div className="audit-list">{[["AL-9921", "ROUND_SETTLED", "Safety Admin", "R-0247"], ["AL-9920", "CLAIM_WINDOW_OPENED", "Worker", "R-0247"], ["AL-9919", "RISK_FLAG_CREATED", "Risk Reviewer", "RF-019"]].map(row => <div key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><small>{row[2]} · {row[3]}</small></div>)}</div></section>; }
function Settings({ action }: { action: (message: string) => void }) { return <section className="panel settings-admin"><div className="panel-head"><div><span className="kicker">GUARDRAILS</span><h2>System configuration</h2></div><span className="state settled">SAFE DEFAULTS</span></div>{[["Real-money operations", "Disabled"], ["TNG integration", "Disabled"], ["Packet provider", "DemoPacketProvider"], ["Telegram auth", "Signed initData outside demo"]].map(row => <div className="setting-row" key={row[0]}><span>{row[0]}</span><b>{row[1]}</b></div>)}<button className="outline-button" onClick={() => action("Configuration changes require a reviewed admin action")}>Request reviewed change</button></section>; }
