import { expect, test } from "@playwright/test";

test("captures the required onboarding, chat, wallet and social visual states", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  test.skip(testInfo.project.name !== "mobile-390x844", "Keep one stable baseline set; responsive coverage remains in miniapp.spec.ts");
  const shot = async (name: string) => page.screenshot({ path: `docs/benchmark/screenshots/${name}.png`, fullPage: true });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "绑定安全设备" })).toBeVisible();
  await shot("visual-qa-01-onboarding-device");
  await page.getByRole("button", { name: /绑定本设备/ }).click();
  await shot("visual-qa-02-onboarding-referrer");
  await page.getByLabel("邀请人 UID / 邀请码").fill("DEMO-INVITE");
  await page.getByRole("button", { name: /继续确认/ }).click();
  await expect(page.getByRole("dialog", { name: "确认绑定这个入口？" })).toBeVisible();
  await shot("visual-qa-03-referrer-confirmation");
  await page.getByRole("button", { name: "确认绑定" }).click();
  await page.getByLabel("安全密码").fill("258036");
  await page.getByLabel("再次输入").fill("258036");
  await shot("visual-qa-04-onboarding-pin");
  await page.getByRole("button", { name: /进入大厅/ }).click();
  await expect(page.getByRole("heading", { name: "游戏大厅" })).toBeVisible();
  await shot("visual-qa-05-hall");
  await page.getByRole("button", { name: /进入游戏聊天室：12牛牛/ }).click();
  await expect(page.locator(".topbar-title h1")).toHaveText("我的聊天");
  await shot("visual-qa-06-chat-list");
  await page.getByRole("button", { name: /进入游戏聊天室：12牛牛/ }).click();
  await expect(page.locator(".topbar-title h1")).toContainText("十二牛牛游戏群");
  await shot("visual-qa-06-internal-chat");
  await page.getByRole("button", { name: "返回" }).click();
  await page.getByRole("button", { name: "钱包", exact: true }).click();
  await expect(page.getByRole("heading", { name: "我的钱包" })).toBeVisible();
  await shot("visual-qa-07-wallet");
  await page.getByRole("button", { name: "聊天", exact: true }).click();
  await expect(page.locator(".topbar-title h1")).toHaveText("我的聊天");
  await page.getByRole("button", { name: /进入游戏聊天室：12牛牛/ }).click();
  await expect(page.locator(".topbar-title h1")).toContainText("十二牛牛游戏群");
  await shot("visual-qa-08-chat-reopened");
  await page.getByRole("button", { name: "返回" }).click();
  await page.getByRole("button", { name: "我", exact: true }).click();
  await shot("visual-qa-09-profile");
  await page.getByRole("button", { name: /语言与通知/ }).click();
  await expect(page.getByRole("heading", { name: "设置" })).toBeVisible();
  await expect(page.getByRole("list", { name: "语言" }).getByRole("button")).toHaveCount(15);
  await shot("visual-qa-10-settings-languages");
  await page.getByRole("button", { name: "返回" }).click();
  await page.getByRole("button", { name: "我", exact: true }).click();
  await page.getByRole("button", { name: /私域关系网络/ }).click();
  await shot("visual-qa-11-referral");
});
