import { expect, test } from "@playwright/test";

test("captures the required onboarding, round, wallet and social visual states", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  test.skip(testInfo.project.name !== "mobile-390x844", "Keep one stable baseline set; responsive coverage remains in miniapp.spec.ts");
  const shot = async (name: string) => page.screenshot({ path: `docs/benchmark/screenshots/${name}.png`, fullPage: true });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "建立你的设备节点" })).toBeVisible();
  await shot("visual-qa-01-onboarding-device");
  await page.getByRole("button", { name: /绑定本设备/ }).click();
  await shot("visual-qa-02-onboarding-referrer");
  await page.getByLabel("邀请人 UID / 邀请码").fill("DEMO-INVITE");
  await page.getByRole("button", { name: /继续确认/ }).click();
  await expect(page.getByRole("dialog", { name: "确认绑定这个入口？" })).toBeVisible();
  await shot("visual-qa-03-referrer-confirmation");
  await page.getByRole("button", { name: "确认绑定" }).click();
  await page.getByLabel("安全密码").fill("258036");
  await page.getByLabel("再次输入").fill("258036");
  await shot("visual-qa-04-onboarding-pin");
  await page.getByRole("button", { name: /进入大厅/ }).click();
  await expect(page.getByRole("heading", { name: "游戏大厅" })).toBeVisible();
  await shot("visual-qa-05-hall");
  await page.getByRole("button", { name: /进入游戏：12牛牛玩法介绍/ }).click();
  await shot("visual-qa-06-game-bidding");
  await page.getByRole("button", { name: /按住确认抢庄/ }).click();
  await shot("visual-qa-07-game-betting");
  await page.getByRole("button", { name: /按住锁定下注/ }).click();
  await shot("visual-qa-08-game-packet");
  await page.getByRole("button", { name: /打开平台红包/ }).click();
  await shot("visual-qa-09-game-claiming");
  await page.getByRole("button", { name: /按住查看结算/ }).click();
  await expect(page.getByRole("heading", { name: "WIN" })).toBeVisible();
  await shot("visual-qa-10-settlement-win");
  await page.getByRole("button", { name: "LOSE" }).click();
  await shot("visual-qa-11-settlement-lose");
  await page.getByRole("button", { name: "TIE" }).click();
  await shot("visual-qa-12-settlement-tie");
  await page.getByRole("button", { name: "WATERED" }).click();
  await shot("visual-qa-13-settlement-watered");
  await page.getByRole("button", { name: /返回游戏大厅/ }).click();
  await page.getByRole("button", { name: "账本", exact: true }).click();
  await shot("visual-qa-14-wallet-ledger");
  await page.getByRole("button", { name: "Telegram", exact: true }).click();
  await shot("visual-qa-15-chat");
  await page.getByRole("button", { name: "我的", exact: true }).click();
  await shot("visual-qa-16-profile");
  await page.getByRole("button", { name: /私域关系网络/ }).click();
  await shot("visual-qa-17-referral");
});
