import { expect, test } from "@playwright/test";

test("captures the required onboarding, round, wallet and social visual states", async ({ page }, testInfo) => {
  test.setTimeout(120_000);
  test.skip(testInfo.project.name !== "mobile-390x844", "Keep one stable baseline set; responsive coverage remains in miniapp.spec.ts");
  const shot = async (name: string) => page.screenshot({ path: `docs/benchmark/screenshots/${name}.png`, fullPage: true });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "新设备登录" })).toBeVisible();
  await shot("visual-qa-01-onboarding-device");
  await page.getByRole("button", { name: /绑定本设备/ }).click();
  await shot("visual-qa-02-onboarding-referrer");
  await page.getByLabel("邀请人 UID").fill("DEMO-INVITE");
  await page.getByRole("button", { name: /下一步/ }).click();
  await expect(page.getByRole("dialog", { name: "绑定此邀请人？" })).toBeVisible();
  await shot("visual-qa-03-referrer-confirmation");
  await page.getByRole("button", { name: "确认绑定" }).click();
  await page.getByLabel("设置 6 位数字密码").fill("258036");
  await page.getByLabel("再次确认").fill("258036");
  await shot("visual-qa-04-onboarding-pin");
  await page.getByRole("button", { name: /完成安全设置/ }).click();
  await expect(page.getByRole("heading", { name: "游戏大厅" })).toBeVisible();
  await shot("visual-qa-05-hall");
  await page.getByRole("button", { name: /玩法介绍/ }).click();
  await shot("visual-qa-06-rules");
  await page.getByRole("button", { name: /进入游戏/ }).click();
  await shot("visual-qa-07-game-bidding");
  await page.getByRole("button", { name: /确认抢庄/ }).click();
  await shot("visual-qa-08-game-empty");
  await page.getByRole("button", { name: /250 DEMO/ }).click();
  await shot("visual-qa-09-game-bet-locked");
  await page.getByRole("button", { name: /领取模拟红包/ }).click();
  await shot("visual-qa-10-game-claiming");
  await page.getByRole("button", { name: /查看并结算/ }).click();
  await expect(page.getByText("已验证结算")).toBeVisible();
  await shot("visual-qa-11-settlement-win");
  await page.getByRole("button", { name: "LOSE" }).click();
  await shot("visual-qa-12-settlement-lose");
  await page.getByRole("button", { name: "TIE" }).click();
  await shot("visual-qa-13-settlement-tie");
  await page.getByRole("button", { name: "WATERED" }).click();
  await shot("visual-qa-14-settlement-watered");
  await page.getByRole("button", { name: /返回游戏大厅/ }).click();
  await page.getByRole("button", { name: "钱包", exact: true }).click();
  await shot("visual-qa-15-wallet-ledger");
  await page.getByRole("button", { name: "聊天", exact: true }).click();
  await shot("visual-qa-16-chat");
  await page.getByRole("button", { name: "我", exact: true }).click();
  await shot("visual-qa-17-profile");
  await page.getByRole("button", { name: /推广与邀请/ }).click();
  await shot("visual-qa-18-referral");
  await page.getByRole("button", { name: "返回" }).click();
  await page.getByRole("button", { name: "我", exact: true }).click();
  await page.getByRole("button", { name: /奖励与排行榜/ }).click();
  await shot("visual-qa-19-missions");
});
